export const COUNTRIES = [
  "Türkiye",
  "Kuzey Kıbrıs Türk Cumhuriyeti",
  "Azerbaycan",
  "Amerika Birleşik Devletleri",
  "İngiltere",
  "Almanya",
] as const;

export type Country = (typeof COUNTRIES)[number];

export const UNIVERSITIES_BY_COUNTRY: Record<Country, string[]> = {
  "Türkiye": [
    "Orta Doğu Teknik Üniversitesi",
    "İstanbul Teknik Üniversitesi",
    "Boğaziçi Üniversitesi",
    "Bilkent Üniversitesi",
    "Koç Üniversitesi",
    "Sabancı Üniversitesi",
    "Hacettepe Üniversitesi",
    "Ankara Üniversitesi",
    "İstanbul Üniversitesi",
    "Ege Üniversitesi",
    "Eskişehir Osmangazi Üniversitesi",
  ],
  "Kuzey Kıbrıs Türk Cumhuriyeti": [
    "Doğu Akdeniz Üniversitesi",
    "Yakın Doğu Üniversitesi",
    "Girne Amerikan Üniversitesi",
    "Lefke Avrupa Üniversitesi",
    "Kıbrıs Uluslararası Üniversitesi",
  ],
  "Azerbaycan": [
    "Bakü Devlet Üniversitesi",
    "Azerbaycan Devlet Petrol ve Sanayi Üniversitesi",
    "ADA Üniversitesi",
    "Azerbaycan Teknik Üniversitesi",
    "Qafqaz Üniversitesi",
  ],
  "Amerika Birleşik Devletleri": [
    "Massachusetts Institute of Technology (MIT)",
    "Stanford University",
    "Harvard University",
    "California Institute of Technology (Caltech)",
    "Carnegie Mellon University",
    "University of California, Berkeley",
    "Princeton University",
    "Yale University",
    "Columbia University",
    "University of Michigan",
  ],
  "İngiltere": [
    "University of Oxford",
    "University of Cambridge",
    "Imperial College London",
    "University College London (UCL)",
    "London School of Economics (LSE)",
    "King's College London",
    "University of Edinburgh",
    "University of Manchester",
    "University of Bristol",
    "University of Warwick",
  ],
  "Almanya": [
    "Technische Universität München (TUM)",
    "Ludwig-Maximilians-Universität München",
    "RWTH Aachen University",
    "Heidelberg University",
    "Humboldt-Universität zu Berlin",
    "Karlsruhe Institute of Technology (KIT)",
    "Technische Universität Berlin",
    "Freie Universität Berlin",
    "University of Stuttgart",
    "University of Hamburg",
  ],
};

export const DEPARTMENTS = [
  // Mühendislik
  "Bilgisayar Mühendisliği",
  "Yazılım Mühendisliği",
  "Yapay Zeka ve Veri Bilimi",
  "Elektrik-Elektronik Mühendisliği",
  "Makine Mühendisliği",
  "İnşaat Mühendisliği",
  "Endüstri Mühendisliği",
  "Kimya Mühendisliği",
  "Biyomedikal Mühendisliği",
  "Havacılık ve Uzay Mühendisliği",
  "Çevre Mühendisliği",
  "Gıda Mühendisliği",
  "Metalurji ve Malzeme Mühendisliği",
  // Temel Bilimler
  "Matematik",
  "Uygulamalı Matematik",
  "İstatistik ve Veri Analizi",
  "Fizik",
  "Kimya",
  "Biyoloji",
  "Biyokimya ve Moleküler Biyoloji",
  "Jeoloji",
  // Sağlık
  "Tıp",
  "Diş Hekimliği",
  "Eczacılık",
  "Hemşirelik",
  "Beslenme ve Diyetetik",
  "Fizyoterapi ve Rehabilitasyon",
  // Sosyal ve İnsan Bilimleri
  "Psikoloji",
  "Sosyoloji",
  "Felsefe",
  "Tarih",
  "Antropoloji",
  // Hukuk ve Siyaset
  "Hukuk",
  "Uluslararası İlişkiler",
  "Siyaset Bilimi ve Kamu Yönetimi",
  // İktisat ve İşletme
  "İktisat",
  "İşletme",
  "Muhasebe ve Finans",
  "Bankacılık ve Sigortacılık",
  "Pazarlama",
  "Yönetim Bilişim Sistemleri",
  "Girişimcilik",
  // Mimarlık ve Tasarım
  "Mimarlık",
  "Şehir ve Bölge Planlama",
  "İç Mimarlık",
  "Endüstriyel Tasarım",
  "Grafik Tasarım",
  // Eğitim
  "Eğitim Bilimleri",
  "Matematik Öğretmenliği",
  "Fen Bilgisi Öğretmenliği",
  "Bilgisayar ve Öğretim Teknolojileri",
  // Dil ve Edebiyat
  "Türk Dili ve Edebiyatı",
  "İngiliz Dili ve Edebiyatı",
  "Çeviribilim",
  "Dilbilim",
  // İletişim ve Medya
  "Gazetecilik",
  "Halkla İlişkiler ve Reklamcılık",
  "Radyo, Televizyon ve Sinema",
  "Yeni Medya",
  // Güzel Sanatlar
  "Güzel Sanatlar",
  "Müzik",
  "Tiyatro ve Performans Sanatları",
  "Resim",
  // Diğer
  "Turizm ve Otelcilik İşletmeciliği",
  "Spor Bilimleri",
  "Harita Mühendisliği",
] as const;
